const {_electron}=require('playwright');const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const out=path.resolve('docs/test-evidence');const report={testedAt:new Date().toISOString(),checks:[]};
const dir=path.resolve('.local/offline-ui-'+Date.now());let application,page;
const note=(name,detail)=>{report.checks.push({name,passed:true,detail});fs.writeFileSync(path.join(out,'desktop-offline.json'),JSON.stringify(report,null,2));console.log('PASS',name)};
const invoke=(method,params)=>page.evaluate(({method,params})=>window.coach.invoke(method,params),{method,params});
async function launch(){application=await _electron.launch({args:[path.resolve('.')],env:{...process.env,COACH_TEST:'1',COACH_USER_DATA:dir}});page=await application.firstWindow();await page.getByRole('button',{name:'运行测试',exact:false}).first().waitFor({timeout:40000});}
const good='class Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        seen = {}\n        for i, value in enumerate(nums):\n            if target - value in seen:\n                return [seen[target - value], i]\n            seen[value] = i\n        return []\n';
(async()=>{try{
 await launch();await page.context().setOffline(true);const b=await invoke('bootstrap');assert.equal(b.problems.length,100);assert.ok(b.problems.every(p=>p.content&&p.templates.python&&p.templates.cpp));note('无浏览器网络时100题缓存及双语言模板可读取');
 await invoke('applySuggestion',{problemId:'1',language:'python',code:good});await page.getByRole('button',{name:'运行测试',exact:false}).first().click();await page.locator('.result-summary').waitFor();assert.match(await page.locator('.result-summary').textContent(),/3\s*\/\s*3/);note('点击运行按钮执行Python代码，3个样例通过');
 const py=await invoke('format',{problemId:'1',language:'python',code:'class Solution:\n def twoSum(self,nums,target):\n  return [0,1]\n'});assert.match(py.code,/def twoSum\(self, nums, target\)/);const cpp=await invoke('format',{problemId:'1',language:'cpp',code:'class Solution{public:vector<int> twoSum(vector<int>& nums,int target){return {0,1};}};'});assert.match(cpp.code,/class Solution/);note('真实Python/C++格式化器可用');
 await page.getByLabel('编程语言',{exact:true}).selectOption('cpp');const cppCode='class Solution { public: vector<int> twoSum(vector<int>& nums, int target) { unordered_map<int,int> seen; for(int i=0;i<(int)nums.size();i++){auto it=seen.find(target-nums[i]); if(it!=seen.end())return {it->second,i}; seen[nums[i]]=i;}return {}; } };';await invoke('applySuggestion',{problemId:'1',language:'cpp',code:cppCode});await page.getByRole('button',{name:'运行测试',exact:false}).first().click();await page.getByRole('button',{name:'停止运行',exact:false}).waitFor();await page.getByRole('button',{name:'运行测试',exact:false}).first().waitFor({timeout:60000});assert.match(await page.locator('.result-summary').textContent(),/3\s*\/\s*3/);note('点击运行按钮编译执行C++17代码，3个样例通过');
 const before=await invoke('bootstrap');await page.getByTitle('下一题',{exact:true}).click();const switched=await invoke('bootstrap');assert.equal(switched.settings.lastProblemId,'49');assert.equal((await invoke('history',{problemId:'49'})).messages.length,0);note('切题独立草稿/对话上下文');await page.getByTitle('上一题',{exact:true}).click();await page.getByLabel('编程语言',{exact:true}).selectOption('python');assert.equal((await invoke('bootstrap')).states['1'].drafts.python,good);note('切题、切语言后双语言草稿保持');
 await page.getByTitle('重置代码（保留可恢复版本）').click();const h=await invoke('history',{problemId:'1'});const v=h.versions.find(v=>v.code===good);assert.ok(v);await invoke('restoreVersion',{problemId:'1',versionId:v.id});assert.equal((await invoke('bootstrap')).states['1'].drafts.python,good);note('重置前快照可恢复');
 await page.getByLabel('独立弹出聊天窗口').click();const popped=await application.waitForEvent('window');await popped.getByLabel('与 AI 教练继续对话').waitFor();note('独立聊天窗口可启动并读取本题上下文');await popped.close();
 await application.evaluate(({BrowserWindow})=>{globalThis.coachTest.mainWindow.setBounds({width:1366,height:820});globalThis.coachTest.mainWindow.webContents.setZoomFactor(1)});await page.screenshot({path:path.join(out,'04-desktop-1366.png')});
 await application.evaluate(({BrowserWindow})=>{globalThis.coachTest.mainWindow.webContents.setZoomFactor(1.25)});await new Promise(r=>setTimeout(r,750));
 const geometry=await page.evaluate(()=>{const box=document.querySelector('.compose-box textarea').getBoundingClientRect();return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,chat:{left:box.left,right:box.right,top:box.top,bottom:box.bottom}}});assert.ok(geometry.scrollWidth<=geometry.width+1,JSON.stringify(geometry));assert.ok(geometry.chat.right<=geometry.width+1&&geometry.chat.bottom<=geometry.height+1,JSON.stringify(geometry));const shot=await application.evaluate(async()=> (await globalThis.coachTest.mainWindow.capturePage()).toDataURL());fs.writeFileSync(path.join(out,'05-desktop-125percent.png'),Buffer.from(shot.split(',')[1],'base64'));note('1366宽与125%缩放：无横向溢出，聊天输入框完整位于视口',geometry);
 await page.getByRole('button',{name:'折叠题面',exact:true}).click();await page.getByRole('button',{name:'展开题面',exact:true}).waitFor();await page.getByRole('button',{name:'展开题面',exact:true}).click();const divider=page.getByRole('separator',{name:'调整题面与编辑器区域'});await divider.focus();await page.keyboard.press('ArrowDown');note('题面折叠/展开及可键盘调节分隔条');
 await page.getByRole('button',{name:'笔记',exact:true}).click();await page.getByLabel('本题笔记').fill('立即关闭窗口前的最后一次输入，应完整保存。');await application.evaluate(({BrowserWindow})=>globalThis.coachTest.mainWindow.close());await application.waitForEvent('close',{timeout:15000});application=null;await launch();const restored=await invoke('bootstrap');assert.equal(restored.states['1'].notes,'立即关闭窗口前的最后一次输入，应完整保存。');note('最后输入后立即关闭窗口，重启笔记完整恢复');
 report.completedAt=new Date().toISOString();fs.writeFileSync(path.join(out,'desktop-offline.json'),JSON.stringify(report,null,2));
 }catch(e){report.failure=e.stack;fs.writeFileSync(path.join(out,'desktop-offline.json'),JSON.stringify(report,null,2));if(page)await page.screenshot({path:path.join(out,'offline-failure.png')}).catch(()=>{});console.error(e);process.exitCode=1}finally{await application?.close().catch(()=>{})}})();
