const {_electron}=require('playwright');const path=require('node:path');const fs=require('node:fs');const assert=require('node:assert/strict');
const exe=process.argv[2];if(!exe)throw new Error('传入已安装的 Hot100 AI Coach.exe 绝对路径');
const report={testedAt:new Date().toISOString(),executable:exe,checks:[]};let app,page;
const save=(name,detail)=>{report.checks.push({name,passed:true,detail});fs.writeFileSync('docs/test-evidence/installed-smoke.json',JSON.stringify(report,null,2));console.log('PASS',name)};
const call=(m,p)=>page.evaluate(([m,p])=>window.coach.invoke(m,p),[m,p]);
(async()=>{try{
 app=await _electron.launch({executablePath:exe,args:[]});page=await app.firstWindow();await page.getByRole('button',{name:'提交并让 GPT 批改',exact:true}).waitFor({timeout:45000});
 const b=await call('bootstrap');assert.equal(b.problems.length,100);assert.ok(b.runtime.python.path.includes('resources'));assert.ok(b.runtime.cpp.path.includes('resources'));save('安装后的独立窗口与100题加载，使用随包解释器和编译器',b.runtime);
 const account=await call('account');assert.equal(account.account.type,'chatgpt');assert.ok(account.models.length);save('随包官方 App Server 连接且保留已有 ChatGPT 登录',{type:account.account.type,modelCount:account.models.length,hasRateLimits:!!account.rateLimits});
 await page.context().setOffline(true);
 const codes={python:'class Solution:\n    def twoSum(self, nums: List[int], target: int) -> List[int]:\n        seen = {}\n        for i, x in enumerate(nums):\n            if target - x in seen:\n                return [seen[target - x], i]\n            seen[x] = i\n        return []\n',cpp:'class Solution { public: vector<int> twoSum(vector<int>& nums,int target){unordered_map<int,int> m;for(int i=0;i<(int)nums.size();i++){if(m.count(target-nums[i]))return {m[target-nums[i]],i};m[nums[i]]=i;}return {};} };'};
 for(const language of ['python','cpp']){const r=await call('run',{problemId:'1',language,code:codes[language]});assert.equal(r.status,'passed',r.error);assert.equal(r.total,3);save('安装版本 '+language+' 真实执行官方样例',{passed:r.passed,total:r.total});const formatted=await call('format',{problemId:'1',language,code:codes[language]});assert.ok(formatted.code);save('安装版本 '+language+' 格式化可用',{formatter:formatted.formatter})}
 const windows=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().map(w=>({id:w.id,title:w.getTitle()})));const windowId=windows[0].id;
 await app.evaluate(({BrowserWindow},id)=>{const w=BrowserWindow.fromId(id);w.setBounds({width:1366,height:820});w.webContents.setZoomFactor(1.25)},windowId);await new Promise(r=>setTimeout(r,1000));
 const g=await page.evaluate(()=>{const r=document.querySelector('.compose-box textarea').getBoundingClientRect();return {width:innerWidth,height:innerHeight,scroll:document.documentElement.scrollWidth,right:r.right,bottom:r.bottom}});assert.ok(g.scroll<=g.width+1&&g.right<=g.width+1&&g.bottom<=g.height+1,JSON.stringify(g));const shot=await app.evaluate(async({BrowserWindow},id)=>(await BrowserWindow.fromId(id).capturePage()).toDataURL(),windowId);fs.writeFileSync('docs/test-evidence/06-installed-native-125percent.png',Buffer.from(shot.split(',')[1],'base64'));save('安装版本125%缩放无溢出，原生窗口截图已保存',g);
 await app.evaluate(({BrowserWindow},id)=>BrowserWindow.fromId(id).webContents.setZoomFactor(1),windowId);report.completedAt=new Date().toISOString();fs.writeFileSync('docs/test-evidence/installed-smoke.json',JSON.stringify(report,null,2));
 }catch(e){report.failure=e.stack;fs.writeFileSync('docs/test-evidence/installed-smoke.json',JSON.stringify(report,null,2));console.error(e);process.exitCode=1}finally{await app?.close().catch(()=>{})}})();
