const test=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {CodexClient}=require('../electron/codex.cjs');
function client(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'coach-model-client-'));t.after(()=>{assert.ok(path.resolve(directory).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(directory,{recursive:true,force:true})});const c=new CodexClient({home:directory,cwd:directory,executable:'mock-only'});c.start=async()=>{};return c;}
test('model catalog follows every cursor, filters hidden entries, and preserves model capabilities',async t=>{const c=client(t),calls=[];c.request=async(method,p)=>{calls.push([method,p]);return p.cursor?{data:[{model:'b',supportedReasoningEfforts:[{reasoningEffort:'max'}]},{model:'a'}],nextCursor:null}:{data:[{model:'a'},{model:'hidden',hidden:true}],nextCursor:'next'}};const models=await c.listModels();assert.deepEqual(models.map(m=>m.model),['a','b']);assert.equal(models[1].supportedReasoningEfforts[0].reasoningEffort,'max');assert.equal(calls.length,2);assert.equal(calls[0][1].includeHidden,false);assert.equal(calls[1][1].cursor,'next');assert.ok(c.modelsUpdatedAt)});
test('invalid, empty, or cyclic model catalog responses fail clearly',async t=>{const c=client(t);c.request=async()=>({data:[]});await assert.rejects(c.listModels(),/未返回/);c.request=async()=>({data:null});await assert.rejects(c.listModels(),/格式无效/);c.request=async()=>({data:[{model:'a'}],nextCursor:'loop'});await assert.rejects(c.listModels(),/分页异常/)});
test('catalog failure remains visible alongside a readable account and independent rate limits',async t=>{const c=client(t);c.request=async method=>method==='account/read'?{account:{type:'chatgpt'}}:{remaining:42};c.listModels=async()=>{throw Error('MOCK model refresh offline')};const a=await c.account();assert.equal(a.account.type,'chatgpt');assert.equal(a.rateLimits.remaining,42);assert.match(a.modelsError,/MOCK model refresh offline/);assert.equal(a.modelsUpdatedAt,null)});
test('forced refresh invalidates only the application model cache and resets the connection',async t=>{const c=client(t),cache=path.join(c.home,'models_cache.json'),auth=path.join(c.home,'auth.json');fs.writeFileSync(cache,'{"old":true}');fs.writeFileSync(auth,'MOCK auth sentinel');let starts=0;c.start=async()=>{starts++};c.ready=Promise.resolve('old-ready');await c.restartForModels();assert.equal(c.ready,null);assert.equal(starts,1);assert.equal(fs.existsSync(cache),false);assert.equal(fs.readFileSync(path.join(c.home,'models_cache.before-refresh.json'),'utf8'),'{"old":true}');assert.equal(fs.readFileSync(auth,'utf8'),'MOCK auth sentinel')});
test('concurrent ordinary account reads share a request and a forced refresh subsequently obtains a fresh catalog',async t=>{const c=client(t);let finish,calls=0;c.readAccount=async p=>{calls++;if(p.refreshModels)return {models:[{model:'new'}]};return new Promise(resolve=>{finish=resolve})};const a=c.account(),b=c.account(),fresh=c.account({refreshModels:true});assert.equal(calls,1);finish({models:[{model:'old'}]});assert.deepEqual((await a).models,(await b).models);assert.equal((await fresh).models[0].model,'new');assert.equal(calls,2);assert.equal(c.accountPending,null)});
