const {_electron}=require('playwright');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),profile=path.join(root,'.local/model-live-'+Date.now()),out=path.join(root,'docs/test-evidence/model-live.json');
fs.mkdirSync(path.dirname(out),{recursive:true});
const report={version:require('../package.json').version,testedAt:new Date().toISOString(),realAI:true,learningProfileIsolated:true,checks:[]};let app,page;
const call=(method,params)=>page.evaluate(([m,p])=>window.coach.invoke(m,p),[method,params]);
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2));
async function complete(count){const deadline=Date.now()+300000;while(Date.now()<deadline){const h=await call('history',{problemId:'sql-1757'}),last=h.messages.filter(m=>m.role==='assistant').at(-1);if(h.messages.length>count&&last&&!['pending','inProgress','streaming'].includes(last.status)){assert.equal(last.status,'completed',last.error||last.text);return h}await new Promise(r=>setTimeout(r,1000))}throw Error('真实AI回复等待超过5分钟')}
(async()=>{try{
 app=await _electron.launch({args:[root],env:{...process.env,COACH_USER_DATA:profile,COACH_TEST:'1'},timeout:45000});page=await app.firstWindow();await page.getByRole('button',{name:'SQL 50',exact:true}).waitFor({timeout:45000});
 const auth=await app.evaluate(async(_,home)=>{const s=globalThis.coachTest.service;await s.account();s.client.close();s.client.home=home;const original=s.client.request.bind(s.client);s.modelProbeCalls=[];s.client.request=(method,p,timeout)=>{if(['turn/start','thread/resume'].includes(method))s.modelProbeCalls.push({method,model:p.model,effort:p.effort});return original(method,p,timeout)};const a=await s.account();s.event({type:'accountChanged',account:a});return {type:a.account?.type,models:a.models.map(m=>m.model||m.id),version:a.appServerVersion}},path.join(process.env.APPDATA,'Hot100 AI Coach','codex'));
 assert.equal(auth.type,'chatgpt');assert.ok(auth.models.includes('gpt-6.1-sol'));report.accountProbe=auth;save();console.log('PASS authenticated latest model catalog',auth.models.length);
 await page.getByRole('button',{name:'SQL 50',exact:true}).click();await page.getByLabel('选择 Codex 模型',{exact:true}).selectOption('gpt-6.1-sol');await page.getByLabel('选择思考强度',{exact:true}).selectOption('high');
 const wrong="SELECT product_id FROM Products WHERE low_fats = 'Y' OR recyclable = 'Y';";await call('applySuggestion',{problemId:'sql-1757',language:'sql',code:wrong});
 await page.getByRole('button',{name:'提交并让 GPT 批改',exact:true}).click();const h=await complete(0),sub=h.submissions[0];assert.equal(sub.model,'gpt-6.1-sol');assert.equal(sub.reasoningEffort,'high');assert.equal(sub.tests.status,'failed');assert.ok(sub.review.length>50);report.checks.push({name:'真实SQL错解批改',model:sub.model,reasoningEffort:sub.reasoningEffort,localPassed:sub.tests.passed,total:sub.tests.total,status:sub.status,review:sub.review});save();console.log('PASS real review with high effort');
 await page.getByLabel('选择思考强度',{exact:true}).selectOption('medium');await page.getByLabel('与 AI 教练继续对话',{exact:true}).fill('接着刚才的批改，请用本题的一行数据说明 OR 和 AND 的区别，控制在三句话，不用给完整答案。');await page.getByRole('button',{name:'发送消息',exact:true}).click();const after=await complete(h.messages.length),answer=after.messages.filter(m=>m.role==='assistant').at(-1);assert.equal(answer.reasoningEffort,'medium');assert.equal(answer.model,'gpt-6.1-sol');assert.ok(answer.text.length>20);report.checks.push({name:'同一对话连续追问并改变强度',model:answer.model,reasoningEffort:answer.reasoningEffort,status:answer.status,text:answer.text});save();console.log('PASS real follow-up with medium effort');
 await page.getByRole('button',{name:'刷新模型',exact:true}).click();await page.locator('.model-feedback').filter({hasText:'已同步'}).waitFor({timeout:45000});const refreshed=await call('account');assert.equal(refreshed.account.type,'chatgpt');assert.ok(refreshed.models.some(m=>m.model==='gpt-6.1-sol'));report.checks.push({name:'强制刷新后账户仍登录且返回最新列表',modelCount:refreshed.models.length,modelsUpdatedAt:refreshed.modelsUpdatedAt});
 await page.getByLabel('与 AI 教练继续对话',{exact:true}).fill('请继续同一题，只用一句话提醒我这个查询最容易混淆的条件。');await page.getByRole('button',{name:'发送消息',exact:true}).click();const resumed=await complete(after.messages.length);assert.equal(resumed.messages.filter(m=>m.role==='assistant').at(-1).reasoningEffort,'medium');
 const calls=await app.evaluate(()=>globalThis.coachTest.service.modelProbeCalls);assert.deepEqual(calls.filter(c=>c.method==='turn/start').map(c=>[c.model,c.effort]),[['gpt-6.1-sol','high'],['gpt-6.1-sol','medium'],['gpt-6.1-sol','medium']]);assert.ok(calls.some(c=>c.method==='thread/resume'));report.protocolCalls=calls;report.checks.push({name:'刷新重启官方进程后恢复同一对话',passed:true});report.passed=true;save();console.log('PASS all real model and effort checks');
}catch(e){report.passed=false;report.error=e.stack||String(e);save();throw e}finally{if(app)await app.close()}})().catch(e=>{console.error(e);process.exitCode=1});
