"""Build the Chinese SQL 50 catalog from cached public official statements.
Expected example rows are parsed from LeetCode; boundary rows are hand specified.
"""
from pathlib import Path
import re, json, html, hashlib
from datetime import datetime, timezone
ROOT=Path(__file__).resolve().parents[1]
CACHE=ROOT/'data/sql-official-cache'
S={}
def add(i,title,rules,constraints,sql,edge,rows,note='',order=False,explain=''):
 S[str(i)]=dict(title=title,rules=rules,constraints=constraints,solution=sql,edge=edge,rows=rows,note=note,order=order,explain=explain)
add(1757,'可回收且低脂的产品','找出同时属于低脂产品并且可回收的产品，返回 product_id。','Products.product_id 唯一。low_fats 和 recyclable 的取值都是 Y 或 N，Y 分别表示低脂、可回收。',"SELECT product_id FROM Products WHERE low_fats='Y' AND recyclable='Y';",{'Products':[[10,'N','Y'],[11,'Y','N'],[12,'N','N']]},[],explain='产品 1 和 3 的两个标记都是 Y，因此满足条件。')
add(584,'寻找用户推荐人','返回推荐人编号不等于 2，或者没有推荐人的顾客姓名 name。','Customer.id 是主键；name 为姓名，referee_id 是推荐人编号，没有推荐人时为 NULL。',"SELECT name FROM Customer WHERE referee_id <> 2 OR referee_id IS NULL;",{'Customer':[[1,'同名',None],[2,'同名',1],[3,'排除',2]]},[['同名'],['同名']],explain='没有推荐人的顾客也应保留；不能只使用 referee_id <> 2。')
add(595,'大的国家','面积至少为 3000000 平方千米，或者人口至少为 25000000 的国家是大国。返回 name、population、area。','World.name 是主键；continent 为所属洲，area 为面积，population 为人口，gdp 为国内生产总值。',"SELECT name,population,area FROM World WHERE area>=3000000 OR population>=25000000;",{'World':[['A','X',3000000,1,0],['B','X',1,25000000,0],['C','X',2999999,24999999,0]]},[['A',1,3000000],['B',25000000,1]])
add(1148,'文章浏览 I','找出至少浏览过一篇自己文章的作者，作者编号输出为 id，去重后按 id 升序返回。','Views 没有主键，可能有重复行。article_id 为文章编号，author_id 为作者，viewer_id 为读者，view_date 为浏览日期。author_id 和 viewer_id 相同表示同一个人。',"SELECT DISTINCT author_id AS id FROM Views WHERE author_id=viewer_id ORDER BY id;",{'Views':[[1,4,4,'2020-01-01'],[1,4,4,'2020-01-01'],[2,2,2,'2020-01-02'],[3,9,4,'2020-01-02']]},[[2],[4]],order=True)
add(1683,'无效的推文','找出内容字符数严格大于 15 的无效推文，返回 tweet_id。','Tweets.tweet_id 是主键。content 只包含字母、数字、感叹号和空格。',"SELECT tweet_id FROM Tweets WHERE length(content)>15;",{'Tweets':[[1,'123456789012345'],[2,'1234567890123456'],[3,'']]},[[2]],note='SQLite 使用 length(content) 统计字符数；原题其他方言可能使用 CHAR_LENGTH。',explain='示例中两条推文长度分别为 11 和 33，只有第二条超过 15。')
add(1378,'使用唯一标识码替换员工 ID','返回每位员工的 unique_id 和 name。没有对应唯一标识码时，unique_id 显示为 NULL。','Employees.id 是主键。EmployeeUNI 的联合主键为 (id, unique_id)，保存员工编号及对应唯一标识码。',"SELECT u.unique_id,e.name FROM Employees e LEFT JOIN EmployeeUNI u ON e.id=u.id;",{'Employees':[[1,'A'],[2,'B']],'EmployeeUNI':[]},[[None,'A'],[None,'B']],explain='Alice 和 Bob 没有对应标识码，结果仍须包含他们，并显示 NULL。')
add(1068,'产品销售分析 I','对 Sales 中的每条销售记录，返回 product_name、year 和 price。price 表示单价，保留不同销售记录形成的重复结果行。','Sales 的联合主键为 (sale_id, year)，product_id 引用 Product.product_id。quantity 为销售数量。Product.product_id 是主键。',"SELECT p.product_name,s.year,s.price FROM Sales s JOIN Product p ON s.product_id=p.product_id;",{'Sales':[[1,8,2020,2,5],[2,8,2020,3,5]],'Product':[[8,'同一商品'],[9,'未售']]},[['同一商品',2020,5],['同一商品',2020,5]])
add(1581,'进店却未进行过交易的顾客','找出曾进店但该次访问没有发生任何交易的顾客，返回 customer_id，以及这种访问的次数 count_no_trans。','Visits.visit_id 唯一，每行表示一次进店。Transactions.transaction_id 唯一，visit_id 表示交易所属的访问，一次访问可能有多笔交易。',"SELECT v.customer_id,COUNT(*) AS count_no_trans FROM Visits v LEFT JOIN Transactions t ON v.visit_id=t.visit_id WHERE t.transaction_id IS NULL GROUP BY v.customer_id;",{'Visits':[[1,8],[2,8],[3,9]],'Transactions':[[1,1,10],[2,1,20]]},[[8,1],[9,1]],explain='顾客 54 有两次无交易访问；顾客 30 和 96 各有一次。一次访问有多笔交易也不能算作无交易访问。')
add(197,'上升的温度','找出温度比前一个自然日更高的记录，返回 id。前一天没有记录时不应纳入结果。','Weather.id 唯一；recordDate 不重复；temperature 为该日温度。日期不保证连续，id 不表示日期顺序。',"SELECT w.id FROM Weather w JOIN Weather p ON p.recordDate=date(w.recordDate,'-1 day') WHERE w.temperature>p.temperature;",{'Weather':[[8,'2020-02-28',10],[1,'2020-02-29',11],[4,'2020-03-02',99],[3,'2020-03-03',99]]},[[1]],note="SQLite 可使用 date(recordDate, '-1 day')；不支持 MySQL 的 DATEDIFF 函数。",explain='2015-01-02 和 2015-01-04 的温度分别高于其前一个自然日。')
add(1661,'每台机器的进程平均运行时间','每个进程的耗时等于 end 时间戳减去 start 时间戳。按机器求进程平均耗时，返回 machine_id、processing_time，平均值四舍五入到小数点后 3 位。','Activity 的联合主键为 (machine_id, process_id, activity_type)。activity_type 为 start 或 end；timestamp 的单位是秒。每个机器与进程组合恰有一条 start 和一条 end，start 早于 end；各机器运行相同数量的进程。',"SELECT s.machine_id,ROUND(AVG(e.timestamp-s.timestamp),3) AS processing_time FROM Activity s JOIN Activity e ON s.machine_id=e.machine_id AND s.process_id=e.process_id AND e.activity_type='end' WHERE s.activity_type='start' GROUP BY s.machine_id;",{'Activity':[[1,1,'start',1.0],[1,1,'end',1.001],[1,2,'start',2.0],[1,2,'end',2.003]]},[[1,0.002]],explain='三台机器各有两个进程；各自结束时间减开始时间后求平均，得到 0.894、0.995、1.456。')
add(577,'员工奖金','返回奖金严格少于 1000 的员工，以及没有奖金记录的员工，输出 name、bonus。没有奖金记录时保留 NULL。','Employee.empId 唯一；supervisor 为主管编号，salary 为工资。Bonus.empId 唯一并引用 Employee.empId。',"SELECT e.name,b.bonus FROM Employee e LEFT JOIN Bonus b ON e.empId=b.empId WHERE b.bonus<1000 OR b.bonus IS NULL;",{'Employee':[[1,'A',None,4000],[2,'B',1,2000],[3,'C',1,2000]],'Bonus':[[1,1000],[2,999]]},[['B',999],['C',None]])
add(1280,'学生们参加各科测试的次数','返回每位学生参加每门科目考试的次数，输出 student_id、student_name、subject_name、attended_exams。即使没有参加某科考试也应显示 0。按 student_id、subject_name 升序排列。','Students.student_id 和 Subjects.subject_name 分别是主键。每位学生都要学习 Subjects 中的全部科目。Examinations 没有主键，允许重复行，每行代表一次参加考试。',"SELECT s.student_id,s.student_name,b.subject_name,COUNT(e.student_id) AS attended_exams FROM Students s CROSS JOIN Subjects b LEFT JOIN Examinations e ON e.student_id=s.student_id AND e.subject_name=b.subject_name GROUP BY s.student_id,s.student_name,b.subject_name ORDER BY s.student_id,b.subject_name;",{'Students':[[2,'B'],[1,'A']],'Subjects':[['Z'],['A']],'Examinations':[[1,'Z'],[1,'Z']]},[[1,'A','A',0],[1,'A','Z',2],[2,'B','A',0],[2,'B','Z',0]],order=True,explain='结果包含全部学生与科目的组合。Alice 的 Math、Physics、Programming 次数为 3、2、1；Alex 的各科次数均为 0。')
add(570,'至少有 5 名直接下属的经理','返回至少拥有 5 名直接下属的经理姓名 name。只统计直接汇报关系。','Employee.id 是主键；department 为部门，managerId 为经理编号。managerId 为 NULL 表示没有经理；员工不会是自己的经理。',"SELECT m.name FROM Employee m JOIN Employee e ON e.managerId=m.id GROUP BY m.id,m.name HAVING COUNT(*)>=5;",{'Employee':[[1,'经理','A',None]]+[[i,'员工'+str(i),'A',1] for i in range(2,6)]},[])
add(1934,'确认率','确认率为 confirmed 消息数除以申请确认的总消息数；从未申请确认的用户确认率为 0。返回每位注册用户的 user_id、confirmation_rate，四舍五入到小数点后 2 位。','Signups.user_id 唯一。Confirmations 的联合主键为 (user_id, time_stamp)，user_id 引用 Signups；action 为 confirmed 或 timeout，分别表示已确认、超时未确认。',"SELECT s.user_id,ROUND(AVG(CASE WHEN c.action='confirmed' THEN 1.0 ELSE 0 END),2) AS confirmation_rate FROM Signups s LEFT JOIN Confirmations c ON s.user_id=c.user_id GROUP BY s.user_id;",{'Signups':[[1,'2020-01-01'],[2,'2020-01-01']],'Confirmations':[[1,'2020-01-02','confirmed'],[1,'2020-01-03','timeout'],[1,'2020-01-04','timeout']]},[[1,0.33],[2,0]],note='SQLite 的整数相除会截断，计算比例时应使用实数，如 1.0 或 100.0。')
add(620,'有趣的电影','返回 id 为奇数且 description 不等于 boring 的电影全部列，按 rating 降序排列。','Cinema.id 是主键；movie 为电影名，description 为描述。rating 为 [0,10] 范围内、保留两位小数的评分。',"SELECT id,movie,description,rating FROM Cinema WHERE id%2=1 AND description<>'boring' ORDER BY rating DESC;",{'Cinema':[[1,'A','boring',10],[2,'B','good',9],[3,'C','good',8],[5,'D','good',9]]},[[5,'D','good',9],[3,'C','good',8]],order=True)
add(1251,'平均售价','按商品计算平均售价：销售总金额除以总销售件数，输出 product_id、average_price，四舍五入到小数点后 2 位。没有售出任何件数的商品平均售价为 0。每次销售须采用购买日期所在价格区间的单价。','Prices 联合主键为 (product_id, start_date, end_date)，同商品的价格区间互不重叠，起止日期都包含在区间内。UnitsSold 可能有重复行，units 为购买件数。',"SELECT p.product_id,COALESCE(ROUND(SUM(p.price*u.units)*1.0/SUM(u.units),2),0) AS average_price FROM Prices p LEFT JOIN UnitsSold u ON p.product_id=u.product_id AND u.purchase_date BETWEEN p.start_date AND p.end_date GROUP BY p.product_id;",{'Prices':[[1,'2020-01-01','2020-01-02',10],[1,'2020-01-03','2020-01-04',20],[2,'2020-01-01','2020-01-04',8]],'UnitsSold':[[1,'2020-01-02',1],[1,'2020-01-03',2]]},[[1,16.67],[2,0]],note='计算加权平均时保留实数，避免整数除法截断。',explain='商品 1 的平均售价为 (100×5+15×20)/115=6.96；商品 2 为 (200×15+30×30)/230=16.96。')
add(1075,'项目员工 I','返回每个项目的 project_id 以及员工平均工作年限 average_years，四舍五入到小数点后 2 位。','Project 的联合主键为 (project_id, employee_id)，employee_id 引用 Employee.employee_id。Employee.employee_id 是主键，experience_years 保证不为 NULL。',"SELECT p.project_id,ROUND(AVG(e.experience_years),2) AS average_years FROM Project p JOIN Employee e ON p.employee_id=e.employee_id GROUP BY p.project_id;",{'Project':[[1,1],[1,2],[2,2]],'Employee':[[1,'A',0],[2,'B',1]]},[[1,0.5],[2,1]])
add(1633,'各赛事的用户注册率','返回每个赛事的 contest_id、percentage；注册率等于该赛事报名人数占全部用户人数的百分比，四舍五入到小数点后 2 位。先按 percentage 降序，相同则按 contest_id 升序。','Users.user_id 是主键。Register 的联合主键为 (contest_id, user_id)，每行代表用户报名一个赛事。',"SELECT contest_id,ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM Users),2) AS percentage FROM Register GROUP BY contest_id ORDER BY percentage DESC,contest_id;",{'Users':[[1,'A'],[2,'B'],[3,'C']],'Register':[[9,1],[8,2],[10,1],[10,2]]},[[10,66.67],[8,33.33],[9,33.33]],order=True)
add(1211,'查询结果的质量和占比','按 query_name 返回 quality 和 poor_query_percentage。quality 是每条记录的 rating/position 的平均值；低质量查询为 rating<3，poor_query_percentage 是它们占该名称全部记录的百分比。两个数值均四舍五入到小数点后 2 位。','Queries 可能包含重复行。position 在 1 到 500 之间，rating 在 1 到 5 之间；result 是查询结果。',"SELECT query_name,ROUND(AVG(rating*1.0/position),2) AS quality,ROUND(AVG(CASE WHEN rating<3 THEN 100.0 ELSE 0 END),2) AS poor_query_percentage FROM Queries GROUP BY query_name;",{'Queries':[['A','x',2,1],['A','x',2,1],['A','y',1,3]]},[['A',1.33,66.67]],note='rating/position 必须以实数计算，例如 rating*1.0/position。')
add(1193,'每月交易 I','按月份与国家返回 month、country、trans_count、approved_count、trans_total_amount、approved_total_amount，分别表示月份、国家、交易数、已批准交易数、交易总金额和已批准交易总金额。month 格式为 YYYY-MM。','Transactions.id 是主键；state 为 approved 或 declined，amount 为金额，trans_date 为交易日期。country 可能为 NULL，应作为一个分组保留。',"SELECT strftime('%Y-%m',trans_date) AS month,country,COUNT(*) AS trans_count,SUM(CASE WHEN state='approved' THEN 1 ELSE 0 END) AS approved_count,SUM(amount) AS trans_total_amount,SUM(CASE WHEN state='approved' THEN amount ELSE 0 END) AS approved_total_amount FROM Transactions GROUP BY month,country;",{'Transactions':[[1,None,'declined',10,'2020-01-01'],[2,None,'approved',20,'2020-01-31'],[3,'CN','declined',30,'2020-02-01']]},[['2020-01',None,2,1,30,20],['2020-02','CN',1,0,30,0]],note="SQLite 可用 strftime('%Y-%m', trans_date) 取年月；不支持 MySQL DATE_FORMAT。")
add(1174,'即时食物配送 II','顾客期望配送日期与下单日期相同的订单称为即时订单，否则是计划订单。找出每位顾客最早下单的那一单，返回这些首单中即时订单的百分比 immediate_percentage，四舍五入到小数点后 2 位。','Delivery.delivery_id 唯一。期望配送日期不早于下单日期；每位顾客恰好有一笔最早订单。',"WITH firsts AS (SELECT customer_id,MIN(order_date) AS first_date FROM Delivery GROUP BY customer_id) SELECT ROUND(AVG(CASE WHEN d.order_date=d.customer_pref_delivery_date THEN 100.0 ELSE 0 END),2) AS immediate_percentage FROM Delivery d JOIN firsts f ON d.customer_id=f.customer_id AND d.order_date=f.first_date;",{'Delivery':[[1,1,'2020-01-01','2020-01-02'],[2,1,'2020-01-02','2020-01-02'],[3,2,'2020-01-01','2020-01-01'],[4,3,'2020-01-01','2020-01-01']]},[[66.67]])
add(550,'游戏玩法分析 IV','返回首次登录后的第二个自然日再次登录的玩家比例 fraction：符合条件的玩家数除以全部玩家数，四舍五入到小数点后 2 位。','Activity 的联合主键为 (player_id, event_date)。每行记录玩家在某天使用某设备登录并玩游戏的数量 games_played，该值可能为 0。',"WITH firsts AS (SELECT player_id,MIN(event_date) AS first_date FROM Activity GROUP BY player_id) SELECT ROUND(AVG(CASE WHEN EXISTS(SELECT 1 FROM Activity a WHERE a.player_id=f.player_id AND a.event_date=date(f.first_date,'+1 day')) THEN 1.0 ELSE 0 END),2) AS fraction FROM firsts f;",{'Activity':[[1,1,'2020-02-28',0],[1,2,'2020-02-29',1],[2,1,'2020-02-28',1],[2,1,'2020-03-01',2],[3,1,'2020-03-01',1]]},[[0.33]],note="SQLite 用 date(日期, '+1 day') 计算次日，日期以 TEXT 保存。")

add(2356,'每位教师所教授的科目种类的数量','返回每位教师 teacher_id 及教授的不同科目数 cnt。同一科目在不同部门授课只算一次。','(subject_id, dept_id) 是联合主键，每行是一位教师在某部门教授的一门科目。',"SELECT teacher_id,COUNT(DISTINCT subject_id) AS cnt FROM Teacher GROUP BY teacher_id;",{'Teacher':[[1,1,1],[1,1,2],[1,2,1],[2,3,1]]},[[1,2],[2,1]])
add(1141,'查询近30天活跃用户数','统计截至 2019-07-27（含当天）的 30 天内每天的活跃用户数，输出 day、active_users。同一用户当天有任意一种活动就算活跃，只计一次；没有活跃用户的日期不输出。','Activity 可有重复行；活动类型为 open_session、end_session、scroll_down、send_message。一个会话只属于一位用户。',"SELECT activity_date AS day,COUNT(DISTINCT user_id) AS active_users FROM Activity WHERE activity_date BETWEEN '2019-06-28' AND '2019-07-27' GROUP BY activity_date;",{'Activity':[[1,1,'2019-06-27','open_session'],[1,2,'2019-06-28','open_session'],[1,2,'2019-06-28','end_session'],[2,3,'2019-07-27','send_message'],[3,4,'2019-07-28','open_session']]},[['2019-06-28',1],['2019-07-27',1]])
add(1070,'产品销售分析 III','找出每种产品最早销售年份的全部销售记录，输出 product_id、first_year、quantity、price。同一产品首年可能有多笔销售，均须保留。','Sales 的 (sale_id, year) 是联合主键。price 为单价，quantity 为销售数量。',"SELECT product_id,year AS first_year,quantity,price FROM Sales WHERE (product_id,year) IN (SELECT product_id,MIN(year) FROM Sales GROUP BY product_id);",{'Sales':[[1,1,2020,2,10],[2,1,2020,3,11],[3,1,2021,8,20],[4,2,2019,4,5]]},[[1,2020,2,10],[1,2020,3,11],[2,2019,4,5]])
add(596,'至少有5名学生的课','返回至少有 5 位学生选修的课程 class。','Courses 的 (student, class) 是联合主键；每行表示一位学生选修一门课。',"SELECT class FROM Courses GROUP BY class HAVING COUNT(*)>=5;",{'Courses':[[str(i),'A'] for i in range(5)]+[[str(i),'B'] for i in range(4)]},[['A']])
add(1729,'求关注者的数量','返回每个用户 user_id 的关注者数量 followers_count，按 user_id 升序排列。','Followers 的 (user_id, follower_id) 是联合主键，每行表示 follower_id 关注 user_id。',"SELECT user_id,COUNT(*) AS followers_count FROM Followers GROUP BY user_id ORDER BY user_id;",{'Followers':[[3,1],[3,2],[1,2]]},[[1,1],[3,2]],order=True)
add(619,'只出现一次的最大数字','找出 MyNumbers 中恰好出现一次的最大数字 num。如果没有只出现一次的数字，仍返回一行，其值为 NULL。','MyNumbers 没有主键，允许重复整数。',"SELECT MAX(num) AS num FROM (SELECT num FROM MyNumbers GROUP BY num HAVING COUNT(*)=1);",{'MyNumbers':[[-2],[-1],[-1]]},[[-2]])
add(1045,'买下所有产品的客户','返回购买了 Product 表中全部产品的客户编号 customer_id。重复购买同一产品不能代替购买其他产品。','Customer 可重复，customer_id 不为 NULL，product_key 引用 Product；Product.product_key 是主键。',"SELECT customer_id FROM Customer GROUP BY customer_id HAVING COUNT(DISTINCT product_key)=(SELECT COUNT(*) FROM Product);",{'Customer':[[1,1],[1,1],[2,1],[2,2]],'Product':[[1],[2]]},[[2]])
add(1731,'每位经理的下属员工数量','至少有一位直接下属的员工视为经理。输出其 employee_id、name、直接下属数 reports_count，以及下属平均年龄 average_age（四舍五入到整数）。按 employee_id 升序。','Employees.employee_id 唯一；reports_to 表示直接上级，没有上级时为 NULL；age 是年龄。',"SELECT m.employee_id,m.name,COUNT(*) AS reports_count,ROUND(AVG(e.age)) AS average_age FROM Employees m JOIN Employees e ON e.reports_to=m.employee_id GROUP BY m.employee_id,m.name ORDER BY m.employee_id;",{'Employees':[[1,'M',None,50],[2,'A',1,20],[3,'B',1,21],[4,'N',None,40]]},[[1,'M',2,21]],order=True)
add(1789,'员工的直属部门','返回每位员工的 employee_id 和主要部门 department_id。属于多个部门时取 primary_flag=Y 的部门；仅属于一个部门时返回该唯一部门。','Employee 的 (employee_id, department_id) 是联合主键。primary_flag 为 Y 或 N；单部门员工的标志为 N，多部门员工有一个主要部门。',"SELECT employee_id,department_id FROM Employee WHERE primary_flag='Y' OR employee_id IN (SELECT employee_id FROM Employee GROUP BY employee_id HAVING COUNT(*)=1);",{'Employee':[[1,7,'N'],[2,7,'N'],[2,8,'Y']]},[[1,7],[2,8]])
add(610,'判断三角形','对每行三条线段长度 x、y、z，判断能否组成三角形。返回 x、y、z、triangle，可组成时为 Yes，否则为 No。','Triangle 的 (x, y, z) 是联合主键。三角形需要任意两边之和严格大于第三边。',"SELECT x,y,z,CASE WHEN x+y>z AND x+z>y AND y+z>x THEN 'Yes' ELSE 'No' END AS triangle FROM Triangle;",{'Triangle':[[1,2,3],[3,4,5],[2,2,2]]},[[1,2,3,'No'],[3,4,5,'Yes'],[2,2,2,'Yes']])
add(180,'连续出现的数字','找出至少连续出现 3 次的数字，去重后输出 ConsecutiveNums。连续性由日志的 id 顺序决定。','Logs.id 是从 1 开始自增的主键；num 为日志中的数字。本地按官方数据库元数据使用 INTEGER 保存 num。',"SELECT DISTINCT a.num AS ConsecutiveNums FROM Logs a JOIN Logs b ON b.id=a.id+1 AND b.num=a.num JOIN Logs c ON c.id=a.id+2 AND c.num=a.num;",{'Logs':[[1,2],[2,2],[3,2],[4,2],[5,3],[6,3],[7,4],[8,3]]},[[2]])
add(1164,'指定日期的产品价格','返回所有产品在 2019-08-16 当天的 product_id 和 price。所有产品初始价格均为 10；有变价记录时取该日期或之前最近一次的新价格。','Products 的 (product_id, change_date) 是联合主键。new_price 表示从 change_date 当天起生效的新价格。',"SELECT DISTINCT p.product_id,COALESCE((SELECT new_price FROM Products q WHERE q.product_id=p.product_id AND change_date<='2019-08-16' ORDER BY change_date DESC LIMIT 1),10) AS price FROM Products p;",{'Products':[[1,20,'2019-08-16'],[1,30,'2019-08-17'],[2,50,'2019-08-17'],[3,7,'2019-08-01']]},[[1,20],[2,10],[3,7]])
add(1204,'最后一个能进入巴士的人','乘客按 turn 从小到大依次上车，巴士载重上限为 1000。返回不超过载重上限的最后一位上车者 person_name，达到恰好 1000 仍可上车。','person_id 和 turn 都唯一，turn 为 1 到 n 的排列，weight 为体重。保证第一位乘客可上车；一轮只能上一人。',"WITH q AS (SELECT person_name,turn,SUM(weight) OVER(ORDER BY turn) AS total FROM Queue) SELECT person_name FROM q WHERE total<=1000 ORDER BY turn DESC LIMIT 1;",{'Queue':[[3,'C',1,3],[1,'A',400,1],[2,'B',600,2]]},[['B']],note='SQLite 支持 SUM(...) OVER(ORDER BY ...) 窗口累计。')
add(1907,'按分类统计薪水','按收入统计账户数 accounts_count，返回三类 category：Low Salary（严格小于 20000）、Average Salary（20000 至 50000，含边界）、High Salary（严格大于 50000）。三类必须全部出现，没有账户的类别计为 0。','Accounts.account_id 是主键，income 为月收入。类别字符串按题目英文保留。',"SELECT 'Low Salary' AS category,COUNT(*) AS accounts_count FROM Accounts WHERE income<20000 UNION ALL SELECT 'Average Salary',COUNT(*) FROM Accounts WHERE income BETWEEN 20000 AND 50000 UNION ALL SELECT 'High Salary',COUNT(*) FROM Accounts WHERE income>50000;",{'Accounts':[[1,20000],[2,50000]]},[['Low Salary',0],['Average Salary',2],['High Salary',0]])
add(1978,'上级经理已离职的公司员工','返回工资严格小于 30000，且上级经理已经离职的员工 employee_id，按 employee_id 升序。没有上级的员工不属于此情况。','Employees.employee_id 是主键。经理离职后其记录会被删除，但下属的 manager_id 保留原编号；无经理时 manager_id 为 NULL。',"SELECT employee_id FROM Employees e WHERE salary<30000 AND manager_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM Employees m WHERE m.employee_id=e.manager_id) ORDER BY employee_id;",{'Employees':[[1,'A',None,10000],[2,'B',9,29999],[3,'C',9,30000],[4,'D',1,20000]]},[[2]],order=True)
add(626,'换座位','每两名相邻学生交换座位 id。学生数为奇数时，最后一人的座位不变。输出 id、student，按 id 升序。','Seat.id 是从 1 开始连续递增的主键。student 为学生姓名。',"SELECT CASE WHEN id%2=0 THEN id-1 WHEN id<(SELECT MAX(id) FROM Seat) THEN id+1 ELSE id END AS id,student FROM Seat ORDER BY id;",{'Seat':[[1,'A']]},[[1,'A']],order=True)
add(1341,'电影评分','输出一列 results、两行结果：第一行为评价电影数量最多的用户姓名，并列时取字典序最小的姓名；第二行为 2020 年 2 月平均评分最高的电影名，并列时取字典序最小的电影名。两项相同也须保留两行。','Movies.movie_id、Users.user_id 为各自主键，Users.name 唯一。MovieRating 的 (movie_id, user_id) 是联合主键；created_at 为评分日期。',"SELECT name AS results FROM (SELECT u.name FROM Users u JOIN MovieRating r ON u.user_id=r.user_id GROUP BY u.user_id,u.name ORDER BY COUNT(*) DESC,u.name LIMIT 1) UNION ALL SELECT title FROM (SELECT m.title FROM Movies m JOIN MovieRating r ON m.movie_id=r.movie_id WHERE created_at>='2020-02-01' AND created_at<'2020-03-01' GROUP BY m.movie_id,m.title ORDER BY AVG(rating) DESC,m.title LIMIT 1);",{'Movies':[[1,'A'],[2,'B']],'Users':[[1,'A'],[2,'B']],'MovieRating':[[1,1,5,'2020-02-29'],[2,2,5,'2020-02-01']]},[['A'],['A']],order=True,note='两行结果可能相同，UNION ALL 保留重复行。')
add(1321,'餐馆营业额变化增长','计算以当天及之前 6 天组成的 7 天窗口的总营业额 amount 和日均营业额 average_amount，输出 visited_on、amount、average_amount。只输出具有完整 7 天窗口的日期，均值四舍五入到两位小数，按 visited_on 升序。','Customer 的 (customer_id, visited_on) 是联合主键。每天至少一位顾客；同一天可能多位顾客，amount 为每位顾客当天支付总额，应先汇总当日营业额。',"WITH daily AS (SELECT visited_on,SUM(amount) AS total FROM Customer GROUP BY visited_on),w AS (SELECT visited_on,SUM(total) OVER(ORDER BY visited_on ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS amount,COUNT(*) OVER(ORDER BY visited_on ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS days FROM daily) SELECT visited_on,amount,ROUND(amount/7.0,2) AS average_amount FROM w WHERE days=7 ORDER BY visited_on;",{'Customer':[[i,'A','2020-01-0'+str(i),10] for i in range(1,9)]+[[20,'B','2020-01-07',7]]},[['2020-01-07',77,11],['2020-01-08',77,11]],order=True)
add(602,'好友申请 II：谁有最多的好友','好友关系视为双向。返回好友数最多者的 id 和好友数 num。','RequestAccepted 的 (requester_id, accepter_id) 是联合主键，accept_date 为接受日期。测试保证只有一位好友数最多者。',"WITH friends AS (SELECT requester_id AS id FROM RequestAccepted UNION ALL SELECT accepter_id FROM RequestAccepted) SELECT id,COUNT(*) AS num FROM friends GROUP BY id ORDER BY num DESC LIMIT 1;",{'RequestAccepted':[[8,1,'2020-01-01'],[2,8,'2020-01-01'],[8,3,'2020-01-01']]},[[8,3]])
add(585,'2016年的投资','累计满足以下两个条件的投保人在 2016 年的投资额 tiv_2016，并四舍五入到两位小数：其 tiv_2015 与至少一位其他投保人相同；其所在地 (lat, lon) 与所有其他人均不同。返回一列 tiv_2016。','Insurance.pid 是主键，lat 和 lon 保证非 NULL。tiv_2015、tiv_2016 分别为两年的投资额，经纬度的组合表示城市。',"SELECT ROUND(SUM(tiv_2016),2) AS tiv_2016 FROM Insurance WHERE tiv_2015 IN (SELECT tiv_2015 FROM Insurance GROUP BY tiv_2015 HAVING COUNT(*)>1) AND (lat,lon) IN (SELECT lat,lon FROM Insurance GROUP BY lat,lon HAVING COUNT(*)=1);",{'Insurance':[[1,10,5.5,1,1],[2,10,6.5,2,2],[3,20,99,3,3],[4,20,88,3,3]]},[[12]])
add(185,'部门工资前三高的所有员工','返回各部门中工资位列前三个不同工资档位的所有员工，列名为 Department、Employee、Salary。同工资并列不能占用多个档位，部门不足三个工资档位时保留全部。','Employee.id、Department.id 分别为主键。Employee.departmentId 引用 Department.id；工资并列时所有符合条件的员工均应返回。',"WITH ranked AS (SELECT e.*,DENSE_RANK() OVER(PARTITION BY departmentId ORDER BY salary DESC) AS rk FROM Employee e) SELECT d.name AS Department,e.name AS Employee,e.salary AS Salary FROM ranked e JOIN Department d ON e.departmentId=d.id WHERE rk<=3;",{'Employee':[[1,'A',100,1],[2,'B',100,1],[3,'C',90,1],[4,'D',80,1],[5,'E',70,1],[6,'F',1,2]],'Department':[[1,'X'],[2,'Y']]},[['X','A',100],['X','B',100],['X','C',90],['X','D',80],['Y','F',1]])
add(1667,'修复表中的名字','修正每个用户的 name，使首字母大写，其余字母小写；输出 user_id、name，按 user_id 升序。','Users.user_id 是主键，name 只包含大小写英文字母。',"SELECT user_id,upper(substr(name,1,1))||lower(substr(name,2)) AS name FROM Users ORDER BY user_id;",{'Users':[[3,'Z'],[1,'aBC'],[2,'ALL']]},[[1,'Abc'],[2,'All'],[3,'Z']],order=True,note='SQLite 使用 substr 截取，|| 拼接字符串；此题只涉及英文字母。')
add(1527,'患某种疾病的患者','返回患 I 型糖尿病者的 patient_id、patient_name、conditions。疾病代码以空格分隔，I 型糖尿病的某个完整疾病代码必须以 DIAB1 开头。','Patients.patient_id 是主键，conditions 可以为空字符串，每个代码不含空格。必须匹配代码开头，不能只在任意位置查找 DIAB1。',"SELECT patient_id,patient_name,conditions FROM Patients WHERE conditions GLOB 'DIAB1*' OR conditions GLOB '* DIAB1*';",{'Patients':[[1,'A','DIAB100'],[2,'B','X DIAB123'],[3,'C','XDIAB100'],[4,'D',''],[5,'E','DIAB2']]},[[1,'A','DIAB100'],[2,'B','X DIAB123']],note='SQLite 不内建 REGEXP，可用 GLOB 匹配字符串；GLOB 的 * 表示任意长度字符。')
add(196,'删除重复的电子邮箱','删除 Person 中重复的电子邮箱记录，每种邮箱仅保留 id 最小的一行。必须编写 DELETE，判题比较执行后 Person 的剩余全部记录，结果行顺序不限。','Person.id 是主键，email 保证仅包含小写字母。编辑器无需建表，删除只作用于本用例的临时内存表。',"DELETE FROM Person WHERE id NOT IN (SELECT MIN(id) FROM Person GROUP BY email);",{'Person':[[5,'a@x.com'],[1,'a@x.com'],[3,'b@x.com'],[2,'a@x.com']]},[[1,'a@x.com'],[3,'b@x.com']],note='SQLite 使用 DELETE FROM Person ...；不支持 MySQL 的 DELETE p1 FROM ... 多表删除形式。')
add(176,'第二高的薪水','返回 Employee 中第二高的不同薪水，列名为 SecondHighestSalary。若不足两个不同薪水，返回一行 NULL。','Employee.id 是主键；相同工资只算一个工资档位。',"SELECT MAX(salary) AS SecondHighestSalary FROM Employee WHERE salary<(SELECT MAX(salary) FROM Employee);",{'Employee':[[1,100],[2,100]]},[[None]])
add(1484,'按日期分组销售产品','按日期返回 sell_date、该日不同商品数量 num_sold、不同商品名组成的 products。商品名去重后按字典序排列，使用英文逗号连接，不添加空格；结果按 sell_date 升序。','Activities 没有主键，允许重复行；product 是商品名。',"SELECT sell_date,COUNT(*) AS num_sold,group_concat(product,',') AS products FROM (SELECT DISTINCT sell_date,product FROM Activities ORDER BY sell_date,product) GROUP BY sell_date ORDER BY sell_date;",{'Activities':[['2020-01-02','Z'],['2020-01-01','B'],['2020-01-01','A'],['2020-01-01','B']]},[['2020-01-01',2,'A,B'],['2020-01-02',1,'Z']],order=True,note='SQLite 的 group_concat 语法与 MySQL 不同，可先在子查询去重、排序，再聚合连接。')
add(1327,'列出指定时间段内所有的下单产品','返回 2020 年 2 月累计订购至少 100 件的商品名 product_name，以及当月总件数 unit。只统计该月份，包含 2 月 29 日。','Products.product_id 是主键；Orders 可能有重复行，product_id 引用 Products。unit 为每笔订单的商品件数。',"SELECT p.product_name,SUM(o.unit) AS unit FROM Products p JOIN Orders o ON p.product_id=o.product_id WHERE o.order_date>='2020-02-01' AND o.order_date<'2020-03-01' GROUP BY p.product_id,p.product_name HAVING SUM(o.unit)>=100;",{'Products':[[1,'A','X'],[2,'B','X']],'Orders':[[1,'2020-02-01',50],[1,'2020-02-29',50],[1,'2020-03-01',200],[2,'2020-02-01',99]]},[['A',100]])
add(1517,'查找拥有有效邮箱的用户','返回拥有有效邮箱的用户全部列 user_id、name、mail。邮箱前缀必须以英文字母开头，后续仅允许大小写英文字母、数字、下划线 _、点 . 和短横线 -；域名必须严格为小写 @leetcode.com。','Users.user_id 是主键；邮箱可能非法。不得接受额外的 @、空前缀、其他域名或大写域名。',"SELECT user_id,name,mail FROM Users WHERE mail GLOB '[A-Za-z]*@leetcode.com' AND substr(mail,1,length(mail)-13) NOT GLOB '*[^A-Za-z0-9_.-]*';",{'Users':[[1,'A','a@leetcode.com'],[2,'B','A_1.-@leetcode.com'],[3,'C','1a@leetcode.com'],[4,'D','a@LEETCODE.COM'],[5,'E','a+b@leetcode.com'],[6,'F','a@b@leetcode.com'],[7,'G','@leetcode.com']]},[[1,'A','a@leetcode.com'],[2,'B','A_1.-@leetcode.com']],note='SQLite 不内建 REGEXP；GLOB 区分大小写，可组合字符集合校验。LIKE 默认对 ASCII 不区分大小写，单用 LIKE 匹配域名会接受大写域名。')

def scalar(v,typ=None):
 if v is None or str(v).lower()=='null':return None
 if typ=='TEXT':return str(v)
 if typ=='INTEGER':return int(v)
 if typ=='REAL':return float(v)
 if re.fullmatch(r'-?\d+',str(v)):return int(v)
 if re.fullmatch(r'-?\d+\.\d+',str(v)):return float(v)
 return str(v)
def plain(content):
 return html.unescape(re.sub(r'<[^>]+>','',content)).replace('\xa0',' ')
def output_tables(content):
 outputs=[]
 for part in re.split(r'\bOutput:\s*',plain(content))[1:]:
  lines=part.splitlines();pipes=[]
  for line in lines:
   if line.strip().startswith('|'):pipes.append([x.strip() for x in line.strip().strip('|').split('|')])
   elif pipes and line.strip() and not line.strip().startswith('+'):break
  assert pipes,part[:100]
  outputs.append({'columns':pipes[0],'rows':[[scalar(x) for x in row] for row in pipes[1:] if not all(re.fullmatch(r'[-: ]+',x) for x in row)]})
 return outputs
def input_examples(q,tables):
 text=q['exampleTestcases'].strip();values=[]
 decoder=json.JSONDecoder()
 while text:
  obj,end=decoder.raw_decode(text);text=text[end:].strip()
  data={}
  for table in tables:
   name=table['name'];names=list(obj['headers'])
   actual=next(n for n in names if n.lower()==name.lower())
   headers=obj['headers'][actual]
   order=[next(i for i,c in enumerate(headers) if c.lower()==col['name'].lower()) for col in table['columns']]
   data[name]=[[scalar(row[j],col['type']) for j,col in zip(order,table['columns'])] for row in obj['rows'][actual]]
  values.append(data)
 return values
def table_html(columns,rows):
 def cell(x):return '<em>NULL</em>' if x is None else html.escape(str(x))
 return '<table><thead><tr>'+''.join('<th>'+html.escape(x)+'</th>' for x in columns)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+cell(v)+'</td>' for v in row)+'</tr>' for row in rows)+'</tbody></table>'
def build():
 plan=json.loads((CACHE/'study-plan.json').read_text(encoding='utf-8-sig'))
 groups=['查询基础','基础连接','聚合函数','排序与分组','高级查询与连接','子查询','字符串与正则']
 problems=[];cases={};refs={}
 for gi,group in enumerate(plan['planSubGroups']):
  for item in group['questions']:
   i=item['questionFrontendId'];spec=S[i];q=json.loads((CACHE/(i+'.json')).read_text(encoding='utf-8-sig'))
   schema=json.loads(q['metaData'])['database_schema']
   tables=[{'name':name,'columns':[{'name':col,'type':'INTEGER' if re.search(r'INT',typ,re.I) else 'REAL' if re.search(r'FLOAT|DOUBLE|DECIMAL|NUMERIC',typ,re.I) else 'TEXT'} for col,typ in cols.items()]} for name,cols in schema.items()]
   expected=output_tables(q['content']);inputs=input_examples(q,tables)
   if i=='1484':
    # The official statement says T-Shirt in input and T-shirt in output.
    # Preserve product spelling from the input; retain unmodified upstream cache.
    expected[0]['rows'][0][2]='Basketball,Headphone,T-Shirt'
    spec['note']+=' 原题公开示例将输入 T-Shirt 写为输出 T-shirt；此处修正输出大小写，与输入商品名保持一致，原文缓存保留。'

   assert len(expected)==len(inputs),(i,len(expected),len(inputs))
   key='sql-'+i;cases[key]=[{'input':[inp],'expected':out,'source':('力扣官方公开示例（修正 T-Shirt 大小写笔误） ' if i=='1484' else '力扣官方公开示例 ')+str(j+1)} for j,(inp,out) in enumerate(zip(inputs,expected))]
   edge={next(n for n in schema if n.lower()==k.lower()):v for k,v in spec['edge'].items()}
   assert set(edge)==set(schema),(i,set(edge),set(schema))
   cases[key].append({'input':[edge],'expected':{'columns':expected[0]['columns'],'rows':spec['rows']},'source':'项目独立编写边界用例（人工核验预期）'})
   sql={'dialect':'sqlite','tables':tables,'orderMatters':spec['order'],'dialectNotes':spec['note']}
   if i=='196':sql.update(mode='delete',resultTable='Person')
   if i=='620':sql['orderBy']=[{'column':'rating','direction':'desc'}]
   content='<p>'+spec['rules']+'</p><h3>表结构</h3>'
   for table in tables:content+='<h4>'+table['name']+'</h4>'+table_html(['字段','本地类型'],[[c['name'],c['type']] for c in table['columns']])
   content+='<h3>说明与约束</h3><p>'+spec['constraints']+'</p><p>'+('结果按上述要求排序。' if spec['order'] else '结果可以按任意顺序返回。')+'</p>'
   for j,case in enumerate(cases[key][:-1]):
    content+='<h3>示例 '+str(j+1)+'</h3><p>输入：</p>'
    for table in tables:content+='<h4>'+table['name']+'</h4>'+table_html([c['name'] for c in table['columns']],case['input'][0][table['name']])
    content+='<p>输出：</p>'+table_html(case['expected']['columns'],case['expected']['rows'])
    if j==0 and spec['explain']:content+='<p>解释：'+spec['explain']+'</p>'
   content+='<h3>本地 SQL 方言</h3><p>本地使用 SQLite 3。'+(spec['note'] or '表数据已自动装入独立内存库，无需创建表或插入数据。')+'</p>'
   url='https://leetcode.com/problems/'+q['titleSlug']+'/'
   problems.append({'id':key,'displayId':i,'kind':'sql','collection':'sql50','title':spec['title'],'slug':q['titleSlug'],'difficulty':q['difficulty'],'category':groups[gi],'tags':['SQL',groups[gi]],'url':url,'content':content,'contentFormat':'html','templates':{'sql':'-- 在下方编写 SQLite '+('DELETE 语句' if i=='196' else '查询')+'\n'},'available':True,'meta':{},'sql':sql,'source':{'url':url,'verifiedAt':datetime.now(timezone.utc).isoformat(),'contentUrl':url,'contentLanguage':'zh-CN','contentMethod':'依据缓存的官方英文题面编写中文译文，保留官方表结构与公开示例','translation':{'kind':'项目中文译文','translatedAt':'2026-09-12','originalLanguage':'en','originalSha256':hashlib.sha256(q['content'].encode()).hexdigest()}}})
   refs[key]=spec['solution']
 assert len(problems)==len(S)==50
 for name,obj in [('data/sql-problems.json',problems),('data/sql-cases.json',cases),('scripts/sql-reference-solutions.json',refs)]:
  (ROOT/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
 print('Built',len(problems),'SQL50 questions;',sum(map(len,cases.values())),'fixtures')
if __name__=='__main__':build()
